spring.application.name=FileXpressBackend
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/filexpress
spring.datasource.username=root
spring.datasource.password=B1Adminn

spring.jpa.hibernate.ddl-auto=update
# debug
spring.jpa.show-sql=true




